In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
df = pd.Series(["Manager", "Senior", "Junior", "Junior", "Junior",
                "Senior", "Senior", "Manager", "Senior", "Manager",
                "Junior", "Senior", "Junior", "Senior", "Manager",
                "Junior","Manager","Senior","Senior","Manager"])

In [7]:
from sklearn.preprocessing import LabelEncoder

In [8]:
le = LabelEncoder()
label_encoded = le.fit_transform(df)




In [19]:
print(label_encoded)
print(le.classes_) 

[1 2 0 0 0 2 2 1 2 1 0 2 0 2 1 0 1 2 2 1]
['Junior' 'Manager' 'Senior']


In [10]:
from sklearn.preprocessing import *

In [11]:
l = OneHotEncoder()

In [14]:
df_2D = df.values.reshape(-1, 1)

encoder = OneHotEncoder()
encoded = encoder.fit_transform(df_2D)

In [16]:
print(encoded)

  (0, 1)	1.0
  (1, 2)	1.0
  (2, 0)	1.0
  (3, 0)	1.0
  (4, 0)	1.0
  (5, 2)	1.0
  (6, 2)	1.0
  (7, 1)	1.0
  (8, 2)	1.0
  (9, 1)	1.0
  (10, 0)	1.0
  (11, 2)	1.0
  (12, 0)	1.0
  (13, 2)	1.0
  (14, 1)	1.0
  (15, 0)	1.0
  (16, 1)	1.0
  (17, 2)	1.0
  (18, 2)	1.0
  (19, 1)	1.0


In [21]:
print(encoded.toarray())   

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]]


In [51]:
df = pd.read_csv("loan_approved.csv")

In [52]:
df

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No   
1    LP001003    Male     Yes          1      Graduate            No   
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
4    LP001008    Male      No          0      Graduate            No   
..        ...     ...     ...        ...           ...           ...   
609  LP002978  Female      No          0      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
611  LP002983    Male     Yes          1      Graduate            No   
612  LP002984    Male     Yes          2      Graduate            No   
613  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0         NaN             360.0   
1               4583             1508.0       128.0             360.0   
2               3000                0.0        66.0             360.0   
3               2583             2358.0       120.0             360.0   
4               6000                0.0       141.0             360.0   
..               ...                ...         ...               ...   
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status (Approved)  
0               1.0         Urban                      Y  
1               1.0         Rural                      N  
2               1.0         Urban                      Y  
3               1.0         Urban                      Y  
4               1.0         Urban                      Y  
..              ...           ...                    ...  
609             1.0         Rural                      Y  
610             1.0         Rural                      Y  
611             1.0         Urban                      Y  
612             1.0         Urban                      Y  
613             0.0     Semiurban                      N  

[614 rows x 13 columns]

In [24]:
df.isnull().sum()

Loan_ID                    0
Gender                    13
Married                    3
Dependents                15
Education                  0
Self_Employed             32
ApplicantIncome            0
CoapplicantIncome          0
LoanAmount                22
Loan_Amount_Term          14
Credit_History            50
Property_Area              0
Loan_Status (Approved)     0
dtype: int64

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Loan_ID                 614 non-null    object 
 1   Gender                  601 non-null    object 
 2   Married                 611 non-null    object 
 3   Dependents              599 non-null    object 
 4   Education               614 non-null    object 
 5   Self_Employed           582 non-null    object 
 6   ApplicantIncome         614 non-null    int64  
 7   CoapplicantIncome       614 non-null    float64
 8   LoanAmount              592 non-null    float64
 9   Loan_Amount_Term        600 non-null    float64
 10  Credit_History          564 non-null    float64
 11  Property_Area           614 non-null    object 
 12  Loan_Status (Approved)  614 non-null    object 
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB


In [72]:
df["Credit_History"] = df["Credit_History"].fillna(df["Credit_History"].mean())

In [27]:
df.isnull().sum()

Loan_ID                    0
Gender                    13
Married                    3
Dependents                15
Education                  0
Self_Employed             32
ApplicantIncome            0
CoapplicantIncome          0
LoanAmount                22
Loan_Amount_Term          14
Credit_History             0
Property_Area              0
Loan_Status (Approved)     0
dtype: int64

In [73]:
df["Loan_Amount_Term"] = df["Loan_Amount_Term"].fillna(df["Loan_Amount_Term"].mean())
df["LoanAmount"] = df["LoanAmount"].fillna(df["LoanAmount"].mean())

In [29]:
df.isnull().sum()

Loan_ID                    0
Gender                    13
Married                    3
Dependents                15
Education                  0
Self_Employed             32
ApplicantIncome            0
CoapplicantIncome          0
LoanAmount                 0
Loan_Amount_Term           0
Credit_History             0
Property_Area              0
Loan_Status (Approved)     0
dtype: int64

In [74]:
df['Gender'].fillna(df['Gender'].mode()[0], inplace=True)
df['Married'].fillna(df['Married'].mode()[0], inplace=True)
df['Dependents'].fillna(df['Dependents'].mode()[0], inplace=True)
df['Self_Employed'].fillna(df['Self_Employed'].mode()[0], inplace=True)


C:\Users\bojja\AppData\Local\Temp\ipykernel_18852\2073488950.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Gender'].fillna(df['Gender'].mode()[0], inplace=True)
C:\Users\bojja\AppData\Local\Temp\ipykernel_18852\2073488950.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

In [75]:
df.isnull().sum()

Loan_ID                   0
Gender                    0
Married                   0
Dependents                0
Education                 0
Self_Employed             0
ApplicantIncome           0
CoapplicantIncome         0
LoanAmount                0
Loan_Amount_Term          0
Credit_History            0
Property_Area             0
Loan_Status (Approved)    0
dtype: int64

In [32]:
df

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No   
1    LP001003    Male     Yes          1      Graduate            No   
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
4    LP001008    Male      No          0      Graduate            No   
..        ...     ...     ...        ...           ...           ...   
609  LP002978  Female      No          0      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
611  LP002983    Male     Yes          1      Graduate            No   
612  LP002984    Male     Yes          2      Graduate            No   
613  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0  146.412162             360.0   
1               4583             1508.0  128.000000             360.0   
2               3000                0.0   66.000000             360.0   
3               2583             2358.0  120.000000             360.0   
4               6000                0.0  141.000000             360.0   
..               ...                ...         ...               ...   
609             2900                0.0   71.000000             360.0   
610             4106                0.0   40.000000             180.0   
611             8072              240.0  253.000000             360.0   
612             7583                0.0  187.000000             360.0   
613             4583                0.0  133.000000             360.0   

     Credit_History Property_Area Loan_Status (Approved)  
0               1.0         Urban                      Y  
1               1.0         Rural                      N  
2               1.0         Urban                      Y  
3               1.0         Urban                      Y  
4               1.0         Urban                      Y  
..              ...           ...                    ...  
609             1.0         Rural                      Y  
610             1.0         Rural                      Y  
611             1.0         Urban                      Y  
612             1.0         Urban                      Y  
613             0.0     Semiurban                      N  

[614 rows x 13 columns]

In [35]:
le = LabelEncoder()
l = le.fit_transform(df["Gender"])

In [36]:
l

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1,

In [37]:
df_2D = df["Married"].values.reshape(-1, 1)

encoder = OneHotEncoder()
encoded = encoder.fit_transform(df_2D)

In [39]:
print(encoded)

  (0, 0)	1.0
  (1, 1)	1.0
  (2, 1)	1.0
  (3, 1)	1.0
  (4, 0)	1.0
  (5, 1)	1.0
  (6, 1)	1.0
  (7, 1)	1.0
  (8, 1)	1.0
  (9, 1)	1.0
  (10, 1)	1.0
  (11, 1)	1.0
  (12, 1)	1.0
  (13, 0)	1.0
  (14, 1)	1.0
  (15, 0)	1.0
  (16, 0)	1.0
  (17, 0)	1.0
  (18, 1)	1.0
  (19, 1)	1.0
  (20, 1)	1.0
  (21, 1)	1.0
  (22, 1)	1.0
  (23, 1)	1.0
  (24, 1)	1.0
  :	:
  (589, 1)	1.0
  (590, 1)	1.0
  (591, 1)	1.0
  (592, 0)	1.0
  (593, 1)	1.0
  (594, 1)	1.0
  (595, 0)	1.0
  (596, 1)	1.0
  (597, 0)	1.0
  (598, 1)	1.0
  (599, 1)	1.0
  (600, 0)	1.0
  (601, 1)	1.0
  (602, 1)	1.0
  (603, 0)	1.0
  (604, 1)	1.0
  (605, 1)	1.0
  (606, 1)	1.0
  (607, 1)	1.0
  (608, 1)	1.0
  (609, 0)	1.0
  (610, 1)	1.0
  (611, 1)	1.0
  (612, 1)	1.0
  (613, 0)	1.0


In [40]:
print(encoded.toarray())

[[1. 0.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [1. 0.]]


In [41]:
df

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No   
1    LP001003    Male     Yes          1      Graduate            No   
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
4    LP001008    Male      No          0      Graduate            No   
..        ...     ...     ...        ...           ...           ...   
609  LP002978  Female      No          0      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
611  LP002983    Male     Yes          1      Graduate            No   
612  LP002984    Male     Yes          2      Graduate            No   
613  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0  146.412162             360.0   
1               4583             1508.0  128.000000             360.0   
2               3000                0.0   66.000000             360.0   
3               2583             2358.0  120.000000             360.0   
4               6000                0.0  141.000000             360.0   
..               ...                ...         ...               ...   
609             2900                0.0   71.000000             360.0   
610             4106                0.0   40.000000             180.0   
611             8072              240.0  253.000000             360.0   
612             7583                0.0  187.000000             360.0   
613             4583                0.0  133.000000             360.0   

     Credit_History Property_Area Loan_Status (Approved)  
0               1.0         Urban                      Y  
1               1.0         Rural                      N  
2               1.0         Urban                      Y  
3               1.0         Urban                      Y  
4               1.0         Urban                      Y  
..              ...           ...                    ...  
609             1.0         Rural                      Y  
610             1.0         Rural                      Y  
611             1.0         Urban                      Y  
612             1.0         Urban                      Y  
613             0.0     Semiurban                      N  

[614 rows x 13 columns]

In [42]:
df["Dependents"].unique()

array(['0', '1', '2', '3+'], dtype=object)

In [43]:
from sklearn.preprocessing import OrdinalEncoder

In [44]:

dependents_order = ["0", "1", "2", "3+"]
education_order = ["Not Graduate", "Graduate"]

ordinal_encoder = OrdinalEncoder(categories=[dependents_order, education_order])

df[["Dependents", "Education"]] = ordinal_encoder.fit_transform(
    df[["Dependents", "Education"]]
)

df[["Dependents", "Education"]].head()


Dependents  Education
0         0.0        1.0
1         1.0        1.0
2         0.0        1.0
3         0.0        0.0
4         0.0        1.0

In [45]:
df[["Dependents", "Education"]]

Dependents  Education
0           0.0        1.0
1           1.0        1.0
2           0.0        1.0
3           0.0        0.0
4           0.0        1.0
..          ...        ...
609         0.0        1.0
610         3.0        1.0
611         1.0        1.0
612         2.0        1.0
613         0.0        1.0

[614 rows x 2 columns]

In [46]:
df

Loan_ID  Gender Married  Dependents  Education Self_Employed  \
0    LP001002    Male      No         0.0        1.0            No   
1    LP001003    Male     Yes         1.0        1.0            No   
2    LP001005    Male     Yes         0.0        1.0           Yes   
3    LP001006    Male     Yes         0.0        0.0            No   
4    LP001008    Male      No         0.0        1.0            No   
..        ...     ...     ...         ...        ...           ...   
609  LP002978  Female      No         0.0        1.0            No   
610  LP002979    Male     Yes         3.0        1.0            No   
611  LP002983    Male     Yes         1.0        1.0            No   
612  LP002984    Male     Yes         2.0        1.0            No   
613  LP002990  Female      No         0.0        1.0           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0  146.412162             360.0   
1               4583             1508.0  128.000000             360.0   
2               3000                0.0   66.000000             360.0   
3               2583             2358.0  120.000000             360.0   
4               6000                0.0  141.000000             360.0   
..               ...                ...         ...               ...   
609             2900                0.0   71.000000             360.0   
610             4106                0.0   40.000000             180.0   
611             8072              240.0  253.000000             360.0   
612             7583                0.0  187.000000             360.0   
613             4583                0.0  133.000000             360.0   

     Credit_History Property_Area Loan_Status (Approved)  
0               1.0         Urban                      Y  
1               1.0         Rural                      N  
2               1.0         Urban                      Y  
3               1.0         Urban                      Y  
4               1.0         Urban                      Y  
..              ...           ...                    ...  
609             1.0         Rural                      Y  
610             1.0         Rural                      Y  
611             1.0         Urban                      Y  
612             1.0         Urban                      Y  
613             0.0     Semiurban                      N  

[614 rows x 13 columns]

In [47]:
df1_2D = df["Self_Employed"].values.reshape(-1, 1)

en = OneHotEncoder()
encoded = encoder.fit_transform(df1_2D)

In [48]:
print(encoded)

  (0, 0)	1.0
  (1, 0)	1.0
  (2, 1)	1.0
  (3, 0)	1.0
  (4, 0)	1.0
  (5, 1)	1.0
  (6, 0)	1.0
  (7, 0)	1.0
  (8, 0)	1.0
  (9, 0)	1.0
  (10, 0)	1.0
  (11, 0)	1.0
  (12, 0)	1.0
  (13, 0)	1.0
  (14, 0)	1.0
  (15, 0)	1.0
  (16, 0)	1.0
  (17, 0)	1.0
  (18, 0)	1.0
  (19, 0)	1.0
  (20, 0)	1.0
  (21, 0)	1.0
  (22, 0)	1.0
  (23, 0)	1.0
  (24, 0)	1.0
  :	:
  (589, 1)	1.0
  (590, 0)	1.0
  (591, 1)	1.0
  (592, 1)	1.0
  (593, 0)	1.0
  (594, 1)	1.0
  (595, 0)	1.0
  (596, 1)	1.0
  (597, 0)	1.0
  (598, 1)	1.0
  (599, 0)	1.0
  (600, 0)	1.0
  (601, 0)	1.0
  (602, 0)	1.0
  (603, 0)	1.0
  (604, 0)	1.0
  (605, 0)	1.0
  (606, 0)	1.0
  (607, 0)	1.0
  (608, 0)	1.0
  (609, 0)	1.0
  (610, 0)	1.0
  (611, 0)	1.0
  (612, 0)	1.0
  (613, 1)	1.0


In [50]:
ohe_married = pd.get_dummies(df["Married"],drop_first = True)
print(ohe_married)


       Yes
0    False
1     True
2     True
3     True
4    False
..     ...
609  False
610   True
611   True
612   True
613  False

[614 rows x 1 columns]


In [57]:

le = LabelEncoder()

m = le.fit_transform(df['Dependents'])

print(df['Dependents'].head())
print(le.classes_)  


0    0
1    1
2    0
3    0
4    0
Name: Dependents, dtype: object
['0' '1' '2' '3+']


In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Loan_ID                 614 non-null    object 
 1   Gender                  614 non-null    object 
 2   Married                 614 non-null    object 
 3   Dependents              614 non-null    object 
 4   Education               614 non-null    object 
 5   Self_Employed           614 non-null    object 
 6   ApplicantIncome         614 non-null    int64  
 7   CoapplicantIncome       614 non-null    float64
 8   LoanAmount              614 non-null    float64
 9   Loan_Amount_Term        614 non-null    float64
 10  Credit_History          614 non-null    float64
 11  Property_Area           614 non-null    object 
 12  Loan_Status (Approved)  614 non-null    object 
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB


In [59]:
df

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No   
1    LP001003    Male     Yes          1      Graduate            No   
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
4    LP001008    Male      No          0      Graduate            No   
..        ...     ...     ...        ...           ...           ...   
609  LP002978  Female      No          0      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
611  LP002983    Male     Yes          1      Graduate            No   
612  LP002984    Male     Yes          2      Graduate            No   
613  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0  146.412162             360.0   
1               4583             1508.0  128.000000             360.0   
2               3000                0.0   66.000000             360.0   
3               2583             2358.0  120.000000             360.0   
4               6000                0.0  141.000000             360.0   
..               ...                ...         ...               ...   
609             2900                0.0   71.000000             360.0   
610             4106                0.0   40.000000             180.0   
611             8072              240.0  253.000000             360.0   
612             7583                0.0  187.000000             360.0   
613             4583                0.0  133.000000             360.0   

     Credit_History Property_Area Loan_Status (Approved)  
0               1.0         Urban                      Y  
1               1.0         Rural                      N  
2               1.0         Urban                      Y  
3               1.0         Urban                      Y  
4               1.0         Urban                      Y  
..              ...           ...                    ...  
609             1.0         Rural                      Y  
610             1.0         Rural                      Y  
611             1.0         Urban                      Y  
612             1.0         Urban                      Y  
613             0.0     Semiurban                      N  

[614 rows x 13 columns]

In [70]:
df["Credit_History"].median()

1.0

In [66]:
df = pd.read_csv("loan_approved.csv")

In [76]:
df.isnull().sum()

Loan_ID                   0
Gender                    0
Married                   0
Dependents                0
Education                 0
Self_Employed             0
ApplicantIncome           0
CoapplicantIncome         0
LoanAmount                0
Loan_Amount_Term          0
Credit_History            0
Property_Area             0
Loan_Status (Approved)    0
dtype: int64

In [77]:
le = LabelEncoder()
l = le.fit_transform(df["Gender"])

In [78]:
l

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1,

In [82]:
df_2D = df["Gender"].values.reshape(-1, 1)

encoder = OneHotEncoder()
encoded = encoder.fit_transform(df_2D)

In [83]:
print(encoded)

  (0, 1)	1.0
  (1, 1)	1.0
  (2, 1)	1.0
  (3, 1)	1.0
  (4, 1)	1.0
  (5, 1)	1.0
  (6, 1)	1.0
  (7, 1)	1.0
  (8, 1)	1.0
  (9, 1)	1.0
  (10, 1)	1.0
  (11, 1)	1.0
  (12, 1)	1.0
  (13, 1)	1.0
  (14, 1)	1.0
  (15, 1)	1.0
  (16, 1)	1.0
  (17, 0)	1.0
  (18, 1)	1.0
  (19, 1)	1.0
  (20, 1)	1.0
  (21, 1)	1.0
  (22, 1)	1.0
  (23, 1)	1.0
  (24, 1)	1.0
  :	:
  (589, 1)	1.0
  (590, 1)	1.0
  (591, 1)	1.0
  (592, 1)	1.0
  (593, 1)	1.0
  (594, 1)	1.0
  (595, 1)	1.0
  (596, 1)	1.0
  (597, 1)	1.0
  (598, 1)	1.0
  (599, 1)	1.0
  (600, 0)	1.0
  (601, 1)	1.0
  (602, 1)	1.0
  (603, 1)	1.0
  (604, 0)	1.0
  (605, 1)	1.0
  (606, 1)	1.0
  (607, 1)	1.0
  (608, 1)	1.0
  (609, 0)	1.0
  (610, 1)	1.0
  (611, 1)	1.0
  (612, 1)	1.0
  (613, 0)	1.0


In [84]:
df_2D = df["Married"].values.reshape(-1, 1)

encoder = OneHotEncoder()
encoded = encoder.fit_transform(df_2D)

In [85]:
print(encoded)

  (0, 0)	1.0
  (1, 1)	1.0
  (2, 1)	1.0
  (3, 1)	1.0
  (4, 0)	1.0
  (5, 1)	1.0
  (6, 1)	1.0
  (7, 1)	1.0
  (8, 1)	1.0
  (9, 1)	1.0
  (10, 1)	1.0
  (11, 1)	1.0
  (12, 1)	1.0
  (13, 0)	1.0
  (14, 1)	1.0
  (15, 0)	1.0
  (16, 0)	1.0
  (17, 0)	1.0
  (18, 1)	1.0
  (19, 1)	1.0
  (20, 1)	1.0
  (21, 1)	1.0
  (22, 1)	1.0
  (23, 1)	1.0
  (24, 1)	1.0
  :	:
  (589, 1)	1.0
  (590, 1)	1.0
  (591, 1)	1.0
  (592, 0)	1.0
  (593, 1)	1.0
  (594, 1)	1.0
  (595, 0)	1.0
  (596, 1)	1.0
  (597, 0)	1.0
  (598, 1)	1.0
  (599, 1)	1.0
  (600, 0)	1.0
  (601, 1)	1.0
  (602, 1)	1.0
  (603, 0)	1.0
  (604, 1)	1.0
  (605, 1)	1.0
  (606, 1)	1.0
  (607, 1)	1.0
  (608, 1)	1.0
  (609, 0)	1.0
  (610, 1)	1.0
  (611, 1)	1.0
  (612, 1)	1.0
  (613, 0)	1.0


In [86]:
le = LabelEncoder()
l = le.fit_transform(df["Dependents"])

In [87]:
l

array([0, 1, 0, 0, 0, 2, 0, 3, 2, 1, 2, 2, 2, 0, 2, 0, 1, 0, 0, 0, 0, 1,
       0, 2, 1, 0, 0, 2, 0, 2, 1, 0, 1, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 2, 1, 2, 0, 0, 1, 2, 0, 3, 0, 1, 0, 0,
       0, 1, 3, 0, 0, 2, 0, 3, 3, 0, 0, 1, 3, 3, 0, 1, 2, 0, 1, 0, 2, 0,
       0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 1, 2, 0, 2, 3,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 2, 0, 0, 3, 0, 1, 0, 0, 0,
       0, 0, 0, 3, 0, 2, 0, 2, 2, 0, 0, 0, 2, 0, 2, 1, 0, 0, 0, 0, 0, 2,
       0, 3, 1, 1, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 2, 0, 3, 3, 0, 0, 0,
       2, 3, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 2, 3, 1, 2, 0, 0, 0, 0, 0, 0, 3, 1, 3, 0, 3, 0, 0, 2, 2,
       0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 2, 1,
       0, 2, 0, 0, 2, 1, 1, 0, 0, 2, 0, 1, 0, 3, 0, 3, 0, 3, 1, 0, 1, 0,
       0, 0, 2, 3, 0, 1, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0,
       0, 0, 0, 0, 0, 2, 2, 0, 0, 3, 1, 1, 0, 1, 0,

In [88]:
df_2D = df["Education"].values.reshape(-1, 1)

encoder = OneHotEncoder()
encoded = encoder.fit_transform(df_2D)

In [89]:
print(encoded)

  (0, 0)	1.0
  (1, 0)	1.0
  (2, 0)	1.0
  (3, 1)	1.0
  (4, 0)	1.0
  (5, 0)	1.0
  (6, 1)	1.0
  (7, 0)	1.0
  (8, 0)	1.0
  (9, 0)	1.0
  (10, 0)	1.0
  (11, 0)	1.0
  (12, 0)	1.0
  (13, 0)	1.0
  (14, 0)	1.0
  (15, 0)	1.0
  (16, 1)	1.0
  (17, 0)	1.0
  (18, 1)	1.0
  (19, 0)	1.0
  (20, 1)	1.0
  (21, 0)	1.0
  (22, 1)	1.0
  (23, 1)	1.0
  (24, 0)	1.0
  :	:
  (589, 0)	1.0
  (590, 0)	1.0
  (591, 0)	1.0
  (592, 0)	1.0
  (593, 0)	1.0
  (594, 0)	1.0
  (595, 1)	1.0
  (596, 1)	1.0
  (597, 0)	1.0
  (598, 0)	1.0
  (599, 0)	1.0
  (600, 0)	1.0
  (601, 1)	1.0
  (602, 0)	1.0
  (603, 0)	1.0
  (604, 0)	1.0
  (605, 1)	1.0
  (606, 0)	1.0
  (607, 1)	1.0
  (608, 0)	1.0
  (609, 0)	1.0
  (610, 0)	1.0
  (611, 0)	1.0
  (612, 0)	1.0
  (613, 0)	1.0


In [90]:
df_2D = df["Self_Employed"].values.reshape(-1, 1)

encoder = OneHotEncoder()
encoded = encoder.fit_transform(df_2D)

In [91]:
print(encoded)

  (0, 0)	1.0
  (1, 0)	1.0
  (2, 1)	1.0
  (3, 0)	1.0
  (4, 0)	1.0
  (5, 1)	1.0
  (6, 0)	1.0
  (7, 0)	1.0
  (8, 0)	1.0
  (9, 0)	1.0
  (10, 0)	1.0
  (11, 0)	1.0
  (12, 0)	1.0
  (13, 0)	1.0
  (14, 0)	1.0
  (15, 0)	1.0
  (16, 0)	1.0
  (17, 0)	1.0
  (18, 0)	1.0
  (19, 0)	1.0
  (20, 0)	1.0
  (21, 0)	1.0
  (22, 0)	1.0
  (23, 0)	1.0
  (24, 0)	1.0
  :	:
  (589, 1)	1.0
  (590, 0)	1.0
  (591, 1)	1.0
  (592, 1)	1.0
  (593, 0)	1.0
  (594, 1)	1.0
  (595, 0)	1.0
  (596, 1)	1.0
  (597, 0)	1.0
  (598, 1)	1.0
  (599, 0)	1.0
  (600, 0)	1.0
  (601, 0)	1.0
  (602, 0)	1.0
  (603, 0)	1.0
  (604, 0)	1.0
  (605, 0)	1.0
  (606, 0)	1.0
  (607, 0)	1.0
  (608, 0)	1.0
  (609, 0)	1.0
  (610, 0)	1.0
  (611, 0)	1.0
  (612, 0)	1.0
  (613, 1)	1.0


In [92]:
df_2D = df["Credit_History"].values.reshape(-1, 1)

encoder = OneHotEncoder()
encoded = encoder.fit_transform(df_2D)

In [93]:
print(encoded)

  (0, 2)	1.0
  (1, 2)	1.0
  (2, 2)	1.0
  (3, 2)	1.0
  (4, 2)	1.0
  (5, 2)	1.0
  (6, 2)	1.0
  (7, 0)	1.0
  (8, 2)	1.0
  (9, 2)	1.0
  (10, 2)	1.0
  (11, 2)	1.0
  (12, 2)	1.0
  (13, 2)	1.0
  (14, 2)	1.0
  (15, 2)	1.0
  (16, 1)	1.0
  (17, 0)	1.0
  (18, 2)	1.0
  (19, 2)	1.0
  (20, 0)	1.0
  (21, 2)	1.0
  (22, 0)	1.0
  (23, 0)	1.0
  (24, 1)	1.0
  :	:
  (589, 0)	1.0
  (590, 2)	1.0
  (591, 2)	1.0
  (592, 2)	1.0
  (593, 2)	1.0
  (594, 2)	1.0
  (595, 2)	1.0
  (596, 2)	1.0
  (597, 0)	1.0
  (598, 2)	1.0
  (599, 2)	1.0
  (600, 1)	1.0
  (601, 2)	1.0
  (602, 2)	1.0
  (603, 2)	1.0
  (604, 2)	1.0
  (605, 2)	1.0
  (606, 2)	1.0
  (607, 2)	1.0
  (608, 2)	1.0
  (609, 2)	1.0
  (610, 2)	1.0
  (611, 2)	1.0
  (612, 2)	1.0
  (613, 0)	1.0


In [94]:
df

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No   
1    LP001003    Male     Yes          1      Graduate            No   
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
4    LP001008    Male      No          0      Graduate            No   
..        ...     ...     ...        ...           ...           ...   
609  LP002978  Female      No          0      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
611  LP002983    Male     Yes          1      Graduate            No   
612  LP002984    Male     Yes          2      Graduate            No   
613  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0  146.412162             360.0   
1               4583             1508.0  128.000000             360.0   
2               3000                0.0   66.000000             360.0   
3               2583             2358.0  120.000000             360.0   
4               6000                0.0  141.000000             360.0   
..               ...                ...         ...               ...   
609             2900                0.0   71.000000             360.0   
610             4106                0.0   40.000000             180.0   
611             8072              240.0  253.000000             360.0   
612             7583                0.0  187.000000             360.0   
613             4583                0.0  133.000000             360.0   

     Credit_History Property_Area Loan_Status (Approved)  
0               1.0         Urban                      Y  
1               1.0         Rural                      N  
2               1.0         Urban                      Y  
3               1.0         Urban                      Y  
4               1.0         Urban                      Y  
..              ...           ...                    ...  
609             1.0         Rural                      Y  
610             1.0         Rural                      Y  
611             1.0         Urban                      Y  
612             1.0         Urban                      Y  
613             0.0     Semiurban                      N  

[614 rows x 13 columns]

In [95]:

encoder = OneHotEncoder()
encoded = encoder.fit_transform(df_2D)

encoded_df = pd.DataFrame(encoded.toarray(), 
                          columns=encoder.get_feature_names_out(["Gender"]))

df = pd.concat([df, encoded_df], axis=1)


In [96]:
df

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No   
1    LP001003    Male     Yes          1      Graduate            No   
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
4    LP001008    Male      No          0      Graduate            No   
..        ...     ...     ...        ...           ...           ...   
609  LP002978  Female      No          0      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
611  LP002983    Male     Yes          1      Graduate            No   
612  LP002984    Male     Yes          2      Graduate            No   
613  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0  146.412162             360.0   
1               4583             1508.0  128.000000             360.0   
2               3000                0.0   66.000000             360.0   
3               2583             2358.0  120.000000             360.0   
4               6000                0.0  141.000000             360.0   
..               ...                ...         ...               ...   
609             2900                0.0   71.000000             360.0   
610             4106                0.0   40.000000             180.0   
611             8072              240.0  253.000000             360.0   
612             7583                0.0  187.000000             360.0   
613             4583                0.0  133.000000             360.0   

     Credit_History Property_Area Loan_Status (Approved)  Gender_0.0  \
0               1.0         Urban                      Y         0.0   
1               1.0         Rural                      N         0.0   
2               1.0         Urban                      Y         0.0   
3               1.0         Urban                      Y         0.0   
4               1.0         Urban                      Y         0.0   
..              ...           ...                    ...         ...   
609             1.0         Rural                      Y         0.0   
610             1.0         Rural                      Y         0.0   
611             1.0         Urban                      Y         0.0   
612             1.0         Urban                      Y         0.0   
613             0.0     Semiurban                      N         1.0   

     Gender_0.8421985815602837  Gender_1.0  
0                          0.0         1.0  
1                          0.0         1.0  
2                          0.0         1.0  
3                          0.0         1.0  
4                          0.0         1.0  
..                         ...         ...  
609                        0.0         1.0  
610                        0.0         1.0  
611                        0.0         1.0  
612                        0.0         1.0  
613                        0.0         0.0  

[614 rows x 16 columns]

In [99]:
df

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No   
1    LP001003    Male     Yes          1      Graduate            No   
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
4    LP001008    Male      No          0      Graduate            No   
..        ...     ...     ...        ...           ...           ...   
609  LP002978  Female      No          0      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
611  LP002983    Male     Yes          1      Graduate            No   
612  LP002984    Male     Yes          2      Graduate            No   
613  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0  146.412162             360.0   
1               4583             1508.0  128.000000             360.0   
2               3000                0.0   66.000000             360.0   
3               2583             2358.0  120.000000             360.0   
4               6000                0.0  141.000000             360.0   
..               ...                ...         ...               ...   
609             2900                0.0   71.000000             360.0   
610             4106                0.0   40.000000             180.0   
611             8072              240.0  253.000000             360.0   
612             7583                0.0  187.000000             360.0   
613             4583                0.0  133.000000             360.0   

     Credit_History Property_Area Loan_Status (Approved)  Gender_0.0  \
0               1.0         Urban                      Y         0.0   
1               1.0         Rural                      N         0.0   
2               1.0         Urban                      Y         0.0   
3               1.0         Urban                      Y         0.0   
4               1.0         Urban                      Y         0.0   
..              ...           ...                    ...         ...   
609             1.0         Rural                      Y         0.0   
610             1.0         Rural                      Y         0.0   
611             1.0         Urban                      Y         0.0   
612             1.0         Urban                      Y         0.0   
613             0.0     Semiurban                      N         1.0   

     Gender_0.8421985815602837  Gender_1.0  
0                          0.0         1.0  
1                          0.0         1.0  
2                          0.0         1.0  
3                          0.0         1.0  
4                          0.0         1.0  
..                         ...         ...  
609                        0.0         1.0  
610                        0.0         1.0  
611                        0.0         1.0  
612                        0.0         1.0  
613                        0.0         0.0  

[614 rows x 16 columns]

In [ ]:

dependents_order = ["0", "1", "2", "3+"]
education_order = ["Not Graduate", "Graduate"]

ordinal_encoder = OrdinalEncoder(categories=[dependents_order, education_order])

df[["Dependents", "Education"]] = ordinal_encoder.fit_transform(
    df[["Dependents", "Education"]]
)

df[["Dependents", "Education"]].head()


In [108]:
df

Loan_ID  Gender Dependents     Education Self_Employed  ApplicantIncome  \
0    LP001002    Male          0      Graduate            No             5849   
1    LP001003    Male          1      Graduate            No             4583   
2    LP001005    Male          0      Graduate           Yes             3000   
3    LP001006    Male          0  Not Graduate            No             2583   
4    LP001008    Male          0      Graduate            No             6000   
..        ...     ...        ...           ...           ...              ...   
609  LP002978  Female          0      Graduate            No             2900   
610  LP002979    Male         3+      Graduate            No             4106   
611  LP002983    Male          1      Graduate            No             8072   
612  LP002984    Male          2      Graduate            No             7583   
613  LP002990  Female          0      Graduate           Yes             4583   

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                  0.0  146.412162             360.0             1.0   
1               1508.0  128.000000             360.0             1.0   
2                  0.0   66.000000             360.0             1.0   
3               2358.0  120.000000             360.0             1.0   
4                  0.0  141.000000             360.0             1.0   
..                 ...         ...               ...             ...   
609                0.0   71.000000             360.0             1.0   
610                0.0   40.000000             180.0             1.0   
611              240.0  253.000000             360.0             1.0   
612                0.0  187.000000             360.0             1.0   
613                0.0  133.000000             360.0             0.0   

    Property_Area Loan_Status (Approved)  Gender_0.0  \
0           Urban                      Y         0.0   
1           Rural                      N         0.0   
2           Urban                      Y         0.0   
3           Urban                      Y         0.0   
4           Urban                      Y         0.0   
..            ...                    ...         ...   
609         Rural                      Y         0.0   
610         Rural                      Y         0.0   
611         Urban                      Y         0.0   
612         Urban                      Y         0.0   
613     Semiurban                      N         1.0   

     Gender_0.8421985815602837  Gender_1.0  Married_No  Married_Yes  
0                          0.0         1.0         1.0          0.0  
1                          0.0         1.0         0.0          1.0  
2                          0.0         1.0         0.0          1.0  
3                          0.0         1.0         0.0          1.0  
4                          0.0         1.0         1.0          0.0  
..                         ...         ...         ...          ...  
609                        0.0         1.0         1.0          0.0  
610                        0.0         1.0         0.0          1.0  
611                        0.0         1.0         0.0          1.0  
612                        0.0         1.0         0.0          1.0  
613                        0.0         0.0         1.0          0.0  

[614 rows x 17 columns]

In [1]:
df

NameError: name 'df' is not defined