In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3])

In [39]:
type(arr1)

numpy.ndarray

In [4]:
type(arr1)

numpy.ndarray

In [5]:
arr1 = np.array([[1,2,3],[4,5,6]])

In [6]:
print(arr1)

[[1 2 3]
 [4 5 6]]


In [7]:
arr1 = arr1*2

In [8]:
arr1

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [9]:
arr2 = np.array([[1,2,3],[2,3,4],[3,4,5]])

In [10]:
arr2

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [11]:
l = [1,2,3]

In [12]:
l = l * 2

In [13]:
l

[1, 2, 3, 1, 2, 3]

In [14]:
a = np.array(l)

In [15]:
a = a*2

In [16]:
a

array([2, 4, 6, 2, 4, 6])

In [17]:
print(arr2.ndim)

2


In [18]:
arr2

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [19]:
print(a.ndim)

1


In [20]:
arr3 = np.array([[[1,2,3],[4,5,6]],[[3,4,5],[9,8,7]]])

In [21]:
print(arr3.ndim)

3


In [22]:
ones = np.ones((2,3))
zeroes = np.zeros((2,3))
random_arr = np.random.random((2,3))

In [23]:
print(ones)
print(zeroes)
print(random_arr)

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[0.16142882 0.66369215 0.487737  ]
 [0.75309875 0.67487594 0.42866539]]


In [25]:
ar = np.arange(0,10,2)

In [26]:
ar

array([0, 2, 4, 6, 8])

In [27]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
np.linspace(1,7,3)

array([1., 4., 7.])

In [29]:
np.linspace(1,10,6)

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

In [30]:
a1 = np.array([[22,25,20],[24,26,23]])

In [31]:
a1

array([[22, 25, 20],
       [24, 26, 23]])

In [32]:
print(a1.shape)
print(a1.size)
print(a1.dtype)
print(a1.ndim)

(2, 3)
6
int32
2


In [33]:
upd_a1 = np.array([[22,25,20],[24,26,23],[21,23,22]])

In [37]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [38]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
Indexing and Slicing:
You are working as a Data Analyst at a fruit distribution company.

The company stores the number of fruit boxes shipped per day (for 1 week) in a 2D NumPy array where:
Each row represents a type of fruit.
Each column represents a day of the week (Mon–Sun).

 
Your Tasks
Create the 2D NumPy array

Create an array named shipments using the above data.
Access single elements (Indexing):
Get the number of Apples shipped on Wednesday.
Get the number of Oranges shipped on Sunday.
Access multiple elements (Slicing):
Extract all the weekday shipments (Mon–Fri) for all fruits.
Extract only the weekend shipments (Sat & Sun).
Extract the shipments of Apples from Wednesday to Saturday.
Bonus (Practice thinking):
Replace the Saturday shipment of Apples (currently 80) with 100 using indexing.
 

In [40]:
a2 = np.array([[50,60,55,70,65,80,90],[40,45,50,60,55,70,75]])

In [49]:
print(a2[:,0:7])

[[50 60 55 70 65 80 90]
 [40 45 50 60 55 70 75]]


In [50]:
a2[0,2]

55

In [51]:
a2[1,6]

75

In [52]:
a2[:,0:5]

array([[50, 60, 55, 70, 65],
       [40, 45, 50, 60, 55]])

In [55]:
a2[0,2:6]

array([55, 70, 65, 80])

In [56]:
a2[0,5] = 100

In [57]:
a2

array([[ 50,  60,  55,  70,  65, 100,  90],
       [ 40,  45,  50,  60,  55,  70,  75]])

In [58]:
c = np.array([1,2,3])
d = np.array([4,5,6])

In [59]:
print(c+d)

[5 7 9]


In [60]:
print(c*d)

[ 4 10 18]


In [61]:
print(c*12)

[12 24 36]


In [62]:
np.dot(c,d)

32

In [63]:
c + 2

array([3, 4, 5])

In [67]:
np.exp(c)


array([ 2.71828183,  7.3890561 , 20.08553692])

In [69]:
np.sqrt(c)

array([1.        , 1.41421356, 1.73205081])

In [70]:
np.log(c)

array([0.        , 0.69314718, 1.09861229])

In [71]:
np.mod(c,2)

array([1, 0, 1], dtype=int32)

In [72]:
np.expm1(c)

array([ 1.71828183,  6.3890561 , 19.08553692])

In [74]:
np.log2(c)

array([0.       , 1.       , 1.5849625])

In [75]:
np.sin(c)

array([0.84147098, 0.90929743, 0.14112001])

In [76]:
np.cos(c)

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [93]:
np.arcsin(c)

C:\Users\bojja\AppData\Local\Temp\ipykernel_8016\1027005417.py:1: RuntimeWarning: invalid value encountered in arcsin
  np.arcsin(c)


array([1.57079633,        nan,        nan])

In [78]:
np.tan(c)

array([ 1.55740772, -2.18503986, -0.14254654])

In [79]:
np.arctan(c)

array([0.78539816, 1.10714872, 1.24904577])

In [80]:
np.degrees(c)

array([ 57.29577951, 114.59155903, 171.88733854])

In [81]:
np.radians(c)

array([0.01745329, 0.03490659, 0.05235988])

In [82]:
np.round(c)

array([1, 2, 3])

In [83]:
np.floor([1.1,2.9,1.5])

array([1., 2., 1.])

In [84]:
np.ceil([1.1,2.9,1.5])

array([2., 3., 2.])

In [85]:
np.trunc([1.1,2.9,1.5])

array([1., 2., 1.])

In [86]:
np.min(c)

1

In [87]:
np.max(c)

3

In [88]:
np.mean(c)

2.0

In [89]:
np.std(c)

0.816496580927726

In [90]:
np.var(c)

0.6666666666666666

In [91]:
np.sum(c)

6

In [92]:
np.prod(c)

6

In [95]:
np.logical_and(c,1)

array([ True,  True,  True])

In [96]:
np.logical_or(c,3)

array([ True,  True,  True])

In [98]:
np.logical_not(c)

array([False, False, False])

In [99]:
np.logical_xor(c,2)

array([False, False, False])

In [102]:
np.greater(c, d)


array([False, False, False])

In [103]:
np.less(c,d)


array([ True,  True,  True])

In [104]:
np.equal(d, c)


array([False, False, False])

In [105]:
np.not_equal(c, d)


array([ True,  True,  True])

In [106]:
np.greater_equal(c, d)


array([False, False, False])

In [107]:
np.less_equal(c, d)

array([ True,  True,  True])

In [108]:
np.bitwise_and(c, d)


array([0, 0, 2])

In [109]:
np.bitwise_or(c, d)


array([5, 7, 7])

In [110]:
np.bitwise_xor(c, d)


array([5, 7, 5])

In [111]:
np.invert(c)

array([-2, -3, -4])

In [112]:
c

array([1, 2, 3])

In [113]:
f1 = np.array([[10,12,11],[9,11,10],[12,13,14],[8,7,9]])

In [115]:
f2 = np.array([[20,19,21],[18,20,19],[22,23,21],[17,18,16]])

In [116]:
f3 = np.array([[15,16,14],[14,13,15],[16,17,18],[12,11,13]])

In [124]:
production_all = np.stack((f1,f2,f3))

In [125]:
production_all

array([[[10, 12, 11],
        [ 9, 11, 10],
        [12, 13, 14],
        [ 8,  7,  9]],

       [[20, 19, 21],
        [18, 20, 19],
        [22, 23, 21],
        [17, 18, 16]],

       [[15, 16, 14],
        [14, 13, 15],
        [16, 17, 18],
        [12, 11, 13]]])

In [126]:
p = np.stack((f1,f2,f3),axis = 0)

In [128]:
production_all.size

36

In [130]:
production_all.shape

(3, 4, 3)

In [131]:
production_all.ndim

3

In [132]:
production_all.dtype

dtype('int32')

In [133]:
production_all.sum(axis = (1,2))

array([126, 234, 174])

In [140]:
production_all.mean(axis = (1,2))

array([10.5, 19.5, 14.5])

In [141]:
production_all.std(axis = (1,2))

array([1.97905701, 1.97905701, 1.97905701])

In [142]:
production_all.var(axis = (1,2))

array([3.91666667, 3.91666667, 3.91666667])

In [143]:
hour_weights = np.array([0.5,1.0,0.75])

In [145]:
np.dot(production_all,hour_weights)

array([[25.25, 23.  , 29.5 , 17.75],
       [44.75, 43.25, 49.75, 38.5 ],
       [34.  , 31.25, 38.5 , 26.75]])

In [150]:
x

In [156]:
production_all = np.stack((f1,f2,f3))

In [152]:
production_all[1]

array([[20, 19, 21],
       [18, 20, 19],
       [22, 23, 21],
       [17, 18, 16]])

In [163]:
for i in range(production_all.shape[0]):
    production_all[i] = production_all[i] - production_all[i].mean()


In [164]:
production_all


array([[[ 0,  1,  0],
        [-1,  0,  0],
        [ 1,  2,  3],
        [-2, -3, -1]],

       [[ 0,  0,  1],
        [-1,  0,  0],
        [ 2,  3,  1],
        [-2, -1, -3]],

       [[ 0,  1,  0],
        [ 0, -1,  0],
        [ 1,  2,  3],
        [-2, -3, -1]]])

In [158]:
production_all

array([[[10, 12, 11],
        [ 9, 11, 10],
        [12, 13, 14],
        [ 8,  7,  9]],

       [[20, 19, 21],
        [18, 20, 19],
        [22, 23, 21],
        [17, 18, 16]],

       [[15, 16, 14],
        [14, 13, 15],
        [16, 17, 18],
        [12, 11, 13]]])

In [159]:
production_all[1] = production_all[1] + 0.5

In [160]:
production_all


array([[[10, 12, 11],
        [ 9, 11, 10],
        [12, 13, 14],
        [ 8,  7,  9]],

       [[20, 19, 21],
        [18, 20, 19],
        [22, 23, 21],
        [17, 18, 16]],

       [[15, 16, 14],
        [14, 13, 15],
        [16, 17, 18],
        [12, 11, 13]]])

In [161]:
    production_all = np.array(production_all)


In [162]:
production_all

array([[[10, 12, 11],
        [ 9, 11, 10],
        [12, 13, 14],
        [ 8,  7,  9]],

       [[20, 19, 21],
        [18, 20, 19],
        [22, 23, 21],
        [17, 18, 16]],

       [[15, 16, 14],
        [14, 13, 15],
        [16, 17, 18],
        [12, 11, 13]]])

In [165]:
c

array([1, 2, 3])

In [166]:
d

array([4, 5, 6])

In [167]:
arr

NameError: name 'arr' is not defined

In [168]:
arr = np.array([1,2,3,23,1,24,2,323,34])

In [170]:
arr.shape

(9,)

In [171]:
arr.reshape(3,3)

array([[  1,   2,   3],
       [ 23,   1,  24],
       [  2, 323,  34]])

In [173]:
np.vstack((c,d))

array([[1, 2, 3],
       [4, 5, 6]])

In [175]:
e = np.hstack((c,d))

In [176]:
e 

array([1, 2, 3, 4, 5, 6])

In [177]:
np.array_split(e,3)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [178]:
e

array([1, 2, 3, 4, 5, 6])

In [179]:
e[e>3]

array([4, 5, 6])

In [180]:
i = [1,3,5]

In [181]:
e[i]

array([2, 4, 6])

In [182]:
e

array([1, 2, 3, 4, 5, 6])

In [183]:
f = np.array([32,2,32,12,43,2])

In [184]:
f

array([32,  2, 32, 12, 43,  2])

In [185]:
v = e.view()

In [186]:
v

array([1, 2, 3, 4, 5, 6])

In [187]:
v[1] = 9

In [188]:
v

array([1, 9, 3, 4, 5, 6])

In [189]:
e

array([1, 9, 3, 4, 5, 6])

In [190]:
cp = e.copy()

In [191]:
cp

array([1, 9, 3, 4, 5, 6])

In [192]:
cp[1] = 2

In [193]:
cp

array([1, 2, 3, 4, 5, 6])

In [194]:
e

array([1, 9, 3, 4, 5, 6])

In [195]:
np.save('copy.npy',cp)

In [197]:
l_arr = np.load('copy.npy')

In [198]:
l_arr

array([1, 2, 3, 4, 5, 6])

In [199]:
n = np.arange(10,51,1)


In [200]:
n

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [201]:
m = np.random.random((3,3))

In [202]:
m

array([[0.2274737 , 0.33704963, 0.02196112],
       [0.5501956 , 0.03941281, 0.6666405 ],
       [0.19869853, 0.48378057, 0.87479269]])

In [203]:
print(n.size)
print(n.shape)
print(n.dtype)

41
(41,)
int32


In [204]:
print(m.size)
print(m.shape)
print(m.dtype)

9
(3, 3)
float64


In [205]:
n = n +5

In [206]:
n

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49, 50, 51, 52, 53, 54, 55])

In [207]:
b1 = np.array([1,2])
c1 = np.array([3,4])

In [208]:
b1*c1

array([3, 8])

In [209]:
am = np.arange(1,26,1)

In [210]:
am

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [213]:
am = am.reshape((5,5))

In [215]:
am

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [216]:
am[0]

array([1, 2, 3, 4, 5])

In [217]:
am[:,4:5]

array([[ 5],
       [10],
       [15],
       [20],
       [25]])

In [218]:
am[0:3,0:2]

array([[ 1,  2],
       [ 6,  7],
       [11, 12]])

In [219]:
arr = np.random.randint(10, 101, size=10)

In [220]:
arr

array([28, 35, 30, 89, 76, 97, 81, 10, 35, 62])

In [221]:
arr.max()

97

In [222]:
arr.min()

10

In [223]:
print(arr.mean())
print(arr.std())

54.3
28.74038969812344


In [224]:
s = np.arange(1,13,1)

In [225]:
s

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [226]:
s.reshape((3,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [227]:
s1 = np.ones((3,3))

In [228]:
s1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [229]:
s2 = np.array([1,2,3])

In [230]:
s1 + s2

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

In [231]:
d1 = np.random.randint(1,51,size = 50)

In [232]:
d1

array([ 9, 43, 35, 38, 41, 22, 38, 11, 44, 33, 31, 35,  2, 42,  6,  9, 39,
       17, 27, 34, 34, 23, 44, 16, 50, 18, 48, 11, 32,  5,  3, 14, 19, 39,
        6, 29, 39, 30, 26, 15,  5, 28, 42, 15, 26, 14, 20, 30,  2, 18])

In [233]:
for i in d1:
    if i%5 ==0 :
        print(i)

35
35
50
5
30
15
5
15
20
30


In [234]:
m1 = np.array([[1,2],[3,4]])
m2 = np.array([[6,7],[8,9]])

In [239]:
np.dot(m1,m2)

array([[22, 25],
       [50, 57]])

In [254]:
f1 = np.random.randint(1,101,size = 16)

In [255]:
f1

array([80, 55, 26, 11, 57, 22, 79, 54, 25, 65, 13, 49, 28, 35, 13, 63])

In [256]:
f1 = f1.reshape((4,4))

In [257]:
f1

array([[80, 55, 26, 11],
       [57, 22, 79, 54],
       [25, 65, 13, 49],
       [28, 35, 13, 63]])

In [258]:
ind=[[0,1,2,3],[0,1,2,3]]

In [262]:
f1[[0,1,2,3],[0,1,2,3]]

array([80, 22, 13, 63])